"""Sample test — auto-generated by goal."""


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the SDK package can be imported."""
    import nlp2dsl_sdk  # noqa: F401
